
[[redirects]]
  from = "/faucetapi/*"
  to = "https://staging-prealpha.scroll.io/faucet/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/early-dev"
  to = "https://scrollzkp.typeform.com/early-dev"

[[redirects]]
  from = "/whitelist/*"
  to = "https://staging-prealpha.scroll.io/whitelist/:splat"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[context.staging.environment]
  REACT_APP_FAUCET_BASE_API_URL="/faucetapi"
  REACT_APP_PREFIX_CLS="scroll"
  REACT_APP_ROLLUPSCAN_BASE_API_URL="https://staging-prealpha.scroll.io/rollupscanapi/api"
  REACT_APP_SCROLL_ENVIRONMENT="STAGING"
  REACT_APP_CHAIN_ID_L1="5343511"
  REACT_APP_CHAIN_ID_L2="5343541"
  REACT_APP_EXTERNAL_RPC_URI_L1="https://staging-prealpha.scroll.io/l1"
  REACT_APP_EXTERNAL_RPC_URI_L2="https://staging-prealpha.scroll.io/l2"
  REACT_APP_EXTERNAL_EXPLORER_URI_L1="https://staging-prealpha.scroll.io/l1scan/"
  REACT_APP_EXTERNAL_EXPLORER_URI_L2="https://staging-prealpha.scroll.io/l2scan/"
  REACT_APP_BASE_URI="https://staging-prealpha.scroll.io"
  REACT_APP_ETH_SYMBOL="TSETH"
  REACT_APP_USDC_SYMBOL="TSUSDC"
  REACT_APP_UNI_V2_TOKEN_SYMBOL="TSUNI2"
  REACT_APP_L1_STANDARD_ERC20_GATEWAY_PROXY_ADDR="0xf6aeab2651Fe834b767f88c0f2B064Dc9FE48b31"                   
  REACT_APP_L2_STANDARD_ERC20_GATEWAY_PROXY_ADDR="0x66826d8665e32456B5F05fd05Ae2Ad41e44000DD"                    
  REACT_APP_L1_GATEWAY_ROUTER_PROXY_ADDR="0x7136311D65Fe0e65eAE4f389a4D86F9Bd731d97C"                    
  REACT_APP_L2_GATEWAY_ROUTER_PROXY_ADDR="0x704dA9Bc96A89b98f7a3890AbA3DeeBB8b69b043"                   
  REACT_APP_L1_USDC_ADDRESS="0xe905a71Ab1C5048D6a6c46BA57E2e22a1fAEF2FF"                    
  REACT_APP_L2_USDC_ADDRESS="0xcbc4965a800018172275afcc3378Bd4F0e953673"
  REACT_APP_L2_UNIV2_ADDRESS="0x4f4eb5ac461c115191390d1760109f1ea185e609"


[context.deploy-preview.environment]
  REACT_APP_FAUCET_BASE_API_URL="/faucetapi"
  REACT_APP_PREFIX_CLS="scroll"
  REACT_APP_ROLLUPSCAN_BASE_API_URL="https://staging-prealpha.scroll.io/rollupscanapi/api"
  REACT_APP_SCROLL_ENVIRONMENT="STAGING"
  REACT_APP_CHAIN_ID_L1="5343511"
  REACT_APP_CHAIN_ID_L2="5343541"
  REACT_APP_EXTERNAL_RPC_URI_L1="https://staging-prealpha.scroll.io/l1"
  REACT_APP_EXTERNAL_RPC_URI_L2="https://staging-prealpha.scroll.io/l2"
  REACT_APP_EXTERNAL_EXPLORER_URI_L1="https://staging-prealpha.scroll.io/l1scan/"
  REACT_APP_EXTERNAL_EXPLORER_URI_L2="https://staging-prealpha.scroll.io/l2scan/"
  REACT_APP_BASE_URI="https://staging-prealpha.scroll.io"
  REACT_APP_ETH_SYMBOL="TSETH"
  REACT_APP_USDC_SYMBOL="TSUSDC"
  REACT_APP_UNI_V2_TOKEN_SYMBOL="TSUNI2"
  REACT_APP_L1_STANDARD_ERC20_GATEWAY_PROXY_ADDR="0xf6aeab2651Fe834b767f88c0f2B064Dc9FE48b31"                   
  REACT_APP_L2_STANDARD_ERC20_GATEWAY_PROXY_ADDR="0x66826d8665e32456B5F05fd05Ae2Ad41e44000DD"                    
  REACT_APP_L1_GATEWAY_ROUTER_PROXY_ADDR="0x7136311D65Fe0e65eAE4f389a4D86F9Bd731d97C"                    
  REACT_APP_L2_GATEWAY_ROUTER_PROXY_ADDR="0x704dA9Bc96A89b98f7a3890AbA3DeeBB8b69b043"                   
  REACT_APP_L1_USDC_ADDRESS="0xe905a71Ab1C5048D6a6c46BA57E2e22a1fAEF2FF"                    
  REACT_APP_L2_USDC_ADDRESS="0xcbc4965a800018172275afcc3378Bd4F0e953673"
  REACT_APP_L2_UNIV2_ADDRESS="0x4f4eb5ac461c115191390d1760109f1ea185e609"

[context.production.environment]
  REACT_APP_FAUCET_BASE_API_URL="/faucetapi"
  REACT_APP_PREFIX_CLS="scroll"
  REACT_APP_ROLLUPSCAN_BASE_API_URL="https://prealpha.scroll.io/rollupscanapi/api"
  REACT_APP_SCROLL_ENVIRONMENT="MAIN"
  REACT_APP_CHAIN_ID_L1="534351"
  REACT_APP_CHAIN_ID_L2="534354"
  REACT_APP_EXTERNAL_RPC_URI_L1="https://prealpha.scroll.io/l1"
  REACT_APP_EXTERNAL_RPC_URI_L2="https://prealpha.scroll.io/l2"
  REACT_APP_EXTERNAL_EXPLORER_URI_L1="https://prealpha.scroll.io/l1scan/"
  REACT_APP_EXTERNAL_EXPLORER_URI_L2="https://prealpha.scroll.io/l2scan/"
  REACT_APP_BASE_URI="https://staging-prealpha.scroll.io"
  REACT_APP_ETH_SYMBOL="TSETH"
  REACT_APP_USDC_SYMBOL="TSUSDC"
  REACT_APP_UNI_V2_TOKEN_SYMBOL="TSUNI2"
  REACT_APP_L1_STANDARD_ERC20_GATEWAY_PROXY_ADDR="0x7F5148aa06E5073cF1577B065152390fe5f3f05b"                   
  REACT_APP_L2_STANDARD_ERC20_GATEWAY_PROXY_ADDR="0x48235a4b7D02F5874dc82F7419cbeaeb0043eF2f"                    
  REACT_APP_L1_GATEWAY_ROUTER_PROXY_ADDR="0x94Cf11667B017e9Fef7Ab557E2eF9EFf6fdfeDc3"                    
  REACT_APP_L2_GATEWAY_ROUTER_PROXY_ADDR="0x8318ed43dD6760dA6A01B7605C408841e7062419"                   
  REACT_APP_L1_USDC_ADDRESS="0xc00FbEf12f2f41dc36C3A928caD93E0C132A2B4B"                    
  REACT_APP_L2_USDC_ADDRESS="0x80732890c93c6D9c6C23E06F888eD0CB88A06018"
  REACT_APP_L2_UNIV2_ADDRESS="0x4f4eb5ac461c115191390d1760109f1ea185e609"

