[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[[redirects]]
  from = "/faucetapi"
  to = "https://staging-prealpha.scroll.io/faucet/:splat"

[[redirects]]
  from = "/whitelist"
  to = "https://staging-prealpha.scroll.io/whitelist/:splat"