name: "Merge production branch back to develop"

on:
  pull_request:
    branches:
      - alpha
    types:
      - closed

jobs:
  create-merge-back-pr:
    if: |
      success() && contains(github.event.pull_request.title , ' [bot]')
    name: "Create PR to merge production branch back to develop"
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v3"
        with:
          fetch-depth: 0
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
      - name: GitHub Pull Request Action
        uses: repo-sync/pull-request@7e79a9f5dc3ad0ce53138f01df2fad14a04831c5
        with:
          pr_title: "ci: merge production branch back to develop [bot]"
          pr_allow_empty: true
          destination_branch: "develop"
          pr_label: "bot/alpha->develop,automerge"
          github_token: ${{ secrets.WRITE_TOKEN }}
